# Generated by Django 6.0.2 on 2026-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='fotos/categoria')),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
        ),
    ]
