# Generated by Django 6.0.2 on 2026-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('preparando', 'Preparando'), ('enviando', 'Enviando'), ('entregue', 'Entregue')], default='preparando', max_length=20),
        ),
    ]
