# Generated by Django 6.0.2 on 2026-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('adm', 'Administrador'), ('superadm', 'Super Administrador')], default='cliente', max_length=20),
        ),
    ]
