# Generated by Django 6.0.2 on 2026-06-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='cliente', max_length=20),
        ),
    ]
