# Generated by Django 6.0.2 on 2026-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_vendida',
            field=models.IntegerField(null=True),
        ),
    ]
