# Generated by Django 6.0.2 on 2026-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_qtd_vendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qtd_vendida',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
