# Generated by Django 6.0.2 on 2026-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='image',
            field=models.ImageField(upload_to='fotos/tipo'),
        ),
    ]
