# Generated by Django 6.0.2 on 2026-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
